// <auto-generated />
using System;
using B4B.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace B4B.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006091353_AddCart")]
    partial class AddCart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("B4B.Api.Models.Firma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfigDegeri")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("Firmalar");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConfigDegeri = "Firma A için örnek yapılandırma değeri",
                            Domain = "localhost:7101",
                            FirmaAdi = "Firma A"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ConfigDegeri = "Firma B için örnek yapılandırma değeri",
                            Domain = "localhost:7201",
                            FirmaAdi = "Firma B"
                        });
                });

            modelBuilder.Entity("B4B.Api.Models.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId", "KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("B4B.Api.Models.Sepet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.HasIndex("FirmaId", "KullaniciId")
                        .IsUnique();

                    b.ToTable("Sepetler");
                });

            modelBuilder.Entity("B4B.Api.Models.SepetKalemi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<Guid>("SepetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.HasIndex("SepetId", "UrunId")
                        .IsUnique();

                    b.ToTable("SepetKalemleri");
                });

            modelBuilder.Entity("B4B.Api.Models.Urun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UrunKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId", "UrunKodu")
                        .IsUnique();

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            FirmaId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Fiyat = 25000m,
                            UrunAdi = "Firma A Laptop",
                            UrunKodu = "A-100"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            FirmaId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Fiyat = 1250m,
                            UrunAdi = "Firma A Klavye",
                            UrunKodu = "A-200"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            FirmaId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Fiyat = 8500m,
                            UrunAdi = "Firma B Monitör",
                            UrunKodu = "B-100"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            FirmaId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Fiyat = 750m,
                            UrunAdi = "Firma B Mouse",
                            UrunKodu = "B-200"
                        });
                });

            modelBuilder.Entity("B4B.Api.Models.Kullanici", b =>
                {
                    b.HasOne("B4B.Api.Models.Firma", "Firma")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("B4B.Api.Models.Sepet", b =>
                {
                    b.HasOne("B4B.Api.Models.Firma", "Firma")
                        .WithMany("Sepetler")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("B4B.Api.Models.Kullanici", "Kullanici")
                        .WithOne("Sepet")
                        .HasForeignKey("B4B.Api.Models.Sepet", "KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("B4B.Api.Models.SepetKalemi", b =>
                {
                    b.HasOne("B4B.Api.Models.Sepet", "Sepet")
                        .WithMany("Kalemler")
                        .HasForeignKey("SepetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("B4B.Api.Models.Urun", "Urun")
                        .WithMany("SepetKalemleri")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sepet");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("B4B.Api.Models.Urun", b =>
                {
                    b.HasOne("B4B.Api.Models.Firma", "Firma")
                        .WithMany("Urunler")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("B4B.Api.Models.Firma", b =>
                {
                    b.Navigation("Kullanicilar");

                    b.Navigation("Sepetler");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("B4B.Api.Models.Kullanici", b =>
                {
                    b.Navigation("Sepet");
                });

            modelBuilder.Entity("B4B.Api.Models.Sepet", b =>
                {
                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("B4B.Api.Models.Urun", b =>
                {
                    b.Navigation("SepetKalemleri");
                });
#pragma warning restore 612, 618
        }
    }
}
